name: Publicar no NPM e GitHub Packages 🚀

on:
  push:
    tags:
      - '*.*.*' # Escuta suas tags do GitFlow (ex: 1.0.1)

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    
    # Permissão para gravar na aba Packages do GitHub
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Setup e Build
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm ci 

      - name: Rodar o Build
        run: npm run build

      # Publicar no NPM
      - name: Configurar Autenticação NPM
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Publicar no NPM (como toc-imports)
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publicar no GitHub Packages (Adiciona "@gualteralbino" devido a exigência)
      - name: Adicionar escopo ao nome do pacote
        run: npm pkg set name="@gualteralbino/toc-imports"

      - name: Configurar Autenticação GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'

      - name: Publicar no GitHub Packages
        run: npm publish
        env:
          # Token nativo do GitHub Actions
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}